global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus se monitore lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Notre API FastAPI
  - job_name: 'fastapi'
    static_configs:
      - targets: ['172.17.0.1:8000']
    metrics_path: '/metrics'
